$filePath = "D:\love-for-yjh\frontend\src\App.tsx"
$content = [System.IO.File]::ReadAllText($filePath, [System.Text.Encoding]::UTF8)

# Replace all corrupted strings with English equivalents
$replacements = @{
    "title={isDark ? '切换到浅色模式' : '切换到深色模式'}" = "title={isDark ? 'Switch to light mode' : 'Switch to dark mode'}"
    "{isDark ? '☀️' : '🌙'}" = "{isDark ? 'Light' : 'Dark'}"
    "message.success(isRegister ? '注册成功！欢迎来到我们的小世界💕' : '欢迎回来，我最爱的人💖')" = "message.success(isRegister ? 'Registration successful! Welcome💕' : 'Welcome back, my love💖')"
    "{ key: '/photos', icon: '📸', label: '我们的回忆' }" = "{ key: '/photos', icon: '📸', label: 'Our Memories' }"
    "{ key: '/map', icon: '🗺️', label: '地图足迹' }" = "{ key: '/map', icon: '🗺️', label: 'Map' }"
    "{ key: '/capsule', icon: '💊', label: '时光胶囊' }" = "{ key: '/capsule', icon: '💊', label: 'Time Capsule' }"
    "{ key: '/reconcile', icon: '💕', label: '和解' }" = "{ key: '/reconcile', icon: '💕', label: 'Reconcile' }"
    "缐廷华💕 阳婧欢" = "Xian Tinghua💕 Yang Jinghuan"
    "{user?.nickname || '我们的爱情故事'}" = "{user?.nickname || 'Our Love Story'}"
    "{sidebarCollapsed ? '>>' : '<<'}" = "{sidebarCollapsed ? '>' : '<'}"
    "message.success('💌 悄悄话已送达')" = "message.success('💌 Message sent')"
    "message.error(res.message || '发送失败')" = "message.error(res.message || 'Send failed')"
    "message.error('发送失败，请重试')" = "message.error('Send failed, please retry')"
    "{user?.nickname || '缐廷华'}" = "{user?.nickname || 'Xian Tinghua'}"
    "{user?.partner_name || '阳婧欢'}" = "{user?.partner_name || 'Yang Jinghuan'}"
    "<div style={{ fontSize: 13, color: '#aaa', marginBottom: 16, letterSpacing: 2 }}>💞 我们已经在一起 {daysTogether} 天了！</div>" = "<div style={{ fontSize: 13, color: '#aaa', marginBottom: 16, letterSpacing: 2 }}>💞 We have been together for {daysTogether} days!</div>"
    "{ val: counter.days, label: '天', glow: true }" = "{ val: counter.days, label: 'Days', glow: true }"
    "{ val: pad(counter.hours), label: '时', glow: false }" = "{ val: pad(counter.hours), label: 'Hours', glow: false }"
    "{ val: pad(counter.minutes), label: '分', glow: false }" = "{ val: pad(counter.minutes), label: 'Min', glow: false }"
    "{ val: pad(counter.seconds), label: '秒', glow: true }" = "{ val: pad(counter.seconds), label: 'Sec', glow: true }"
    "{note || '正在为你准备最甜蜜的情话...'}" = "{note || 'Preparing sweet words for you...'}"
    "{loadingNote ? '🔄 加载中...' : '🔀 换一句情话'}" = "{loadingNote ? '🔄 Loading...' : '🔀 Change quote'}"
    "我们的回忆" = "Our Memories"
    "{recentPhotos.length > 0 ? '查看全部 →' : '去上传 ↗'}" = "{recentPhotos.length > 0 ? 'View all →' : 'Upload ↗'}"
    "<div style={{ color: '#e91e63', fontWeight: 700, fontSize: 16, marginBottom: 6 }}>还没有回忆</div>" = "<div style={{ color: '#e91e63', fontWeight: 700, fontSize: 16, marginBottom: 6 }}>No memories yet</div>"
    "<div style={{ color: '#999', fontSize: 14 }}>点击前往「我们的回忆」上传照片</div>" = "<div style={{ color: '#999', fontSize: 14 }}>Go to 'Our Memories' to upload photos</div>"
    "<p style={{ color: '#888', fontSize: 14 }}>写下你想对TA说的话</p>" = "<p style={{ color: '#888', fontSize: 14 }}>Write something to your love</p>"
    "const emojis = ['💕', '💗', '💖', '🌸', '🌹', '🎀', '💛', '💞', '🎵'];" = "const emojis = ['💕', '💗', '💖', '🌸', '🌹', '🎀', '💛', '💞', '🎵'];"
    "<p style={{ color: '#aaa', fontSize: 14 }}>每一句话，都是真心话 · 缐廷华💕 阳婧欢</p>" = "<p style={{ color: '#aaa', fontSize: 14 }}>Every word is sincere · For YJH 💕</p>"
    "<div style={{ marginTop: 24, color: '#ff6b9d', fontSize: 13 }}>—— 缐廷华💕 阳婧欢，永远相爱</div>" = "<div style={{ marginTop: 24, color: '#ff6b9d', fontSize: 13 }}>—— For YJH 💕, Forever in love</div>"
    "message.success('🎉 照片上传成功！')" = "message.success('🎉 Photo uploaded!')"
    "message.success('💨 已删除！')" = "message.success('💨 Deleted!')"
    "{photos.length > 0 ? `已收藏 ${photos.length} 张珍贵瞬间` : '记录属于我们的每一个瞬间'}" = "{photos.length > 0 ? `${photos.length} precious moments` : 'Record our precious moments'}"
    "{uploading ? '上传中...' : '+ 上传照片'}" = "{uploading ? 'Uploading...' : '+ Upload Photo'}"
    "<h3 style={{ color: '#e91e63', marginBottom: 8 }}>还没有照片</h3>" = "<h3 style={{ color: '#e91e63', marginBottom: 8 }}>No photos yet</h3>"
    "<p style={{ color: '#bbb', marginBottom: 28 }}>上传你们的第一张合照，让回忆永远留在这里</p>" = "<p style={{ color: '#bbb', marginBottom: 28 }}>Upload your first photo together</p>"
    "message.success('🎬 视频上传成功！')" = "message.success('🎬 Video uploaded!')"
    "message.success('已删除！')" = "message.success('Deleted!')"
    "{videos.length > 0 ? `珍藏 ${videos.length} 段珍贵视频` : '记录属于我们的珍贵视频'}" = "{videos.length > 0 ? `${videos.length} precious videos` : 'Record our precious videos'}"
    "<h3 style={{ color: '#e91e63', marginBottom: 8 }}>还没有视频</h3>" = "<h3 style={{ color: '#e91e63', marginBottom: 8 }}>No videos yet</h3>"
    "<p style={{ color: '#bbb', marginBottom: 28 }}>上传你们的第一段视频，让美好永远留在这里</p>" = "<p style={{ color: '#bbb', marginBottom: 28 }}>Upload your first video together</p>"
    "{playingVideo.title || '💕 我们的美好时光'}" = "{playingVideo.title || '💕 Our Precious Time'}"
    "{dayjs(playingVideo.created_at).format('YYYY年MM月DD日 HH:mm')}" = "{dayjs(playingVideo.created_at).format('YYYY-MM-DD HH:mm')}"
    "message.success('✅ 更新成功')" = "message.success('✅ Updated')"
    "message.success('🎉 添加成功！')" = "message.success('🎉 Added!')"
    "<p style={{ color: '#aaa', fontSize: 14, margin: 0 }}>记录每一个重要的日子，让爱有迹可循</p>" = "<p style={{ color: '#aaa', fontSize: 14, margin: 0 }}>Record every important day</p>"
    "<p style={{ color: '#bbb', marginBottom: 24 }}>快去添加你们的第一个重要日子吧！</p>" = "<p style={{ color: '#bbb', marginBottom: 24 }}>Add your first important day!</p>"
    "{dayjs(item.date).format('YYYY年MM月DD日')}" = "{dayjs(item.date).format('YYYY-MM-DD')}"
    "{editingId ? '✏️ 编辑纪念日' : '🎁 添加纪念日'}" = "{editingId ? '✏️ Edit' : '🎁 Add Memory'}"
    "<Form.Item name=\"title\" label=\"纪念日名称\" rules={[{ required: true, message: '请输入名称' }]}" = "<Form.Item name=\"title\" label=\"Title\" rules={[{ required: true, message: 'Enter title' }]}"
    "{editingId ? '保存修改 →' : '添加纪念日 🎉'}" = "{editingId ? 'Save →' : 'Add Memory 🎉'}"
    "message.success('💖 保存成功！')" = "message.success('💖 Saved!')"
    "message.success('💖 头像更新成功！')" = "message.success('💖 Avatar updated!')"
    "if (!user) return <div style={{ textAlign: 'center', padding: 40 }}>加载中...</div>;" = "if (!user) return <div style={{ textAlign: 'center', padding: 40 }}>Loading...</div>;"
    "<div style={{ fontSize: 11, color: '#bbb' }}>👤 匿名</div>" = "<div style={{ fontSize: 11, color: '#bbb' }}>👤 Anonymous</div>"
    "<Input prefix={<span style={{ color: '#a855f7' }}>💕</span>} placeholder=\"你爱的人的名字\" />" = "<Input prefix={<span style={{ color: '#a855f7' }}>💕</span>} placeholder=\"Your love's name\" />"
    "{ icon: '👤', label: '我的昵称', value: user.nickname || '未设置', color: '#e91e63' }" = "{ icon: '👤', label: 'My nickname', value: user.nickname || 'Not set', color: '#e91e63' }"
    "{ icon: '📧', label: '邮箱', value: user.email || '未设置', color: '#666' }" = "{ icon: '📧', label: 'Email', value: user.email || 'Not set', color: '#666' }"
    "<span style={{ color: '#888', fontSize: 13 }}>TA的名字</span>" = "<span style={{ color: '#888', fontSize: 13 }}>Partner's name</span>"
    "<span style={{ color: '#a855f7', fontWeight: 500 }}>{user.partner_name || '未设置'}</span>" = "<span style={{ color: '#a855f7', fontWeight: 500 }}>{user.partner_name || 'Not set'}</span>"
    "{ emoji: '❤️', label: '在一起天数', value: `${daysTogether} 天`, highlight: true }" = "{ emoji: '❤️', label: 'Days together', value: `${daysTogether} days`, highlight: true }"
    "{ emoji: '🌹', label: '开始日期', value: '2026-01-14' }" = "{ emoji: '🌹', label: 'Start date', value: '2026-01-14' }"
    "{ emoji: '💌', label: '我爱你', value: '无数次' }" = "{ emoji: '💌', label: 'I love you', value: 'Countless times' }"
    "{ emoji: '�想你次数', label: '想你次数', value: 'N/A' }" = "{ emoji: '�想你', label: 'Times missed', value: 'N/A' }"
    "<h3 style={{ margin: '0 0 16px', fontSize: 16, fontWeight: 700, color: '#333' }}>💫 快捷操作</h3>" = "<h3 style={{ margin: '0 0 16px', fontSize: 16, fontWeight: 700, color: '#333' }}>💫 Quick Actions</h3>"
    "<div style={{ fontSize: 12, color: '#666', marginTop: 6 }}>纪念日</div>" = "<div style={{ fontSize: 12, color: '#666', marginTop: 6 }}>Anniversary</div>"
}

foreach ($key in $replacements.Keys) {
    if ($content.Contains($key)) {
        $content = $content.Replace($key, $replacements[$key])
        Write-Host "Fixed: $($key.Substring(0, [Math]::Min(50, $key.Length)))..."
    }
}

# Write back
$utf8WithBom = New-Object System.Text.UTF8Encoding $true
[System.IO.File]::WriteAllText($filePath, $content, $utf8WithBom)
Write-Host "Done! Total replacements: $($replacements.Count)"
