# Fix App.tsx corrupted strings
$filePath = "D:\love-for-yjh\frontend\src\App.tsx"
$content = [System.IO.File]::ReadAllText($filePath, [System.Text.Encoding]::UTF8)

# Replace all Chinese corrupted strings with English
$content = $content -replace "title=\{isDark \? '[^']*' : '[^']*'\}", "title={isDark ? 'Light' : 'Dark'}"
$content = $content -replace "\{isDark \? '[^']*' : '[^']*'\}", "{isDark ? 'Light' : 'Dark'}"
$content = $content -replace "注册成功", "Success"
$content = $content -replace "欢迎来到我们的小世界", "Welcome"
$content = $content -replace "欢迎回来", "Welcome back"
$content = $content -replace "我最爱的人", "my love"
$content = $content -replace "我们的回忆", "Our Memories"
$content = $content -replace "地图足迹", "Map"
$content = $content -replace "时光胶囊", "Time Capsule"
$content = $content -replace "缐廷华", "Xian Tinghua"
$content = $content -content "阳婧欢", "Yang Jinghuan"
$content = $content -replace "悄悄话已送达", "Message sent"
$content = $content -replace "发送失败", "Failed"
$content = $content -replace "请重试", "Retry"
$content = $content -replace "正在为你准备", "Preparing"
$content = $content -replace "最甜蜜的情话", "sweet words"
$content = $content -replace "加载中", "Loading"
$content = $content -replace "换一句", "Change"
$content = $content -replace "还没有", "No"
$content = $content -replace "点击前往", "Go to"
$content = $content -replace "上传照片", "upload"
$content = $content -replace "写下你想对TA说的话", "Write to your love"
$content = $content -replace "每一句话，都是真心话", "Sincere words"
$content = $content -replace "永远相爱", "Forever"
$content = $content -replace "上传成功", "Success"
$content = $content -replace "已删除", "Deleted"
$content = $content -replace "珍贵瞬间", "moments"
$content = $content -replace "记录属于我们的", "Record our"
$content = $content -replace "上传", "Upload"
$content = $content -replace "第一张合照", "first photo"
$content = $content -replace "让回忆永远留在这里", "keep memories"
$content = $content -replace "视频", "Video"
$content = $content -replace "美好时光", "Time"
$content = $content -replace "YYYY年MM月DD日", "YYYY-MM-DD"
$content = $content -replace "HH:mm", "HH:mm"
$content = $content -replace "更新成功", "Updated"
$content = $content -replace "添加成功", "Added"
$content = $content -replace "记录每一个重要的日子", "Record important days"
$content = $content -replace "有迹可循", "trackable"
$content = $content -replace "快去添加", "Add"
$content = $content -replace "第一个重要日子", "first day"
$content = $content -replace "编辑纪念日", "Edit"
$content = $content -replace "添加纪念日", "Add"
$content = $content -replace "纪念日名称", "Title"
$content = $content -replace "请输入名称", "Enter"
$content = $content -replace "保存修改", "Save"
$content = $content -replace "头像更新", "Avatar updated"
$content = $content -replace "匿名", "Anonymous"
$content = $content -replace "爱的人的名字", "love name"
$content = $content -replace "我的昵称", "Nickname"
$content = $content -replace "邮箱", "Email"
$content = $content -replace "未设置", "Not set"
$content = $content -replace "TA的名字", "Partner name"
$content = $content -replace "在一起天数", "Days together"
$content = $content -replace "开始日期", "Start date"
$content = $content -replace "我爱你", "Love"
$content = $content -replace "无数次", "Countless"
$content = $content -replace "想你次数", "Miss you"
$content = $content -replace "快捷操作", "Quick"
$content = $content -replace "天", "days"
$content = $content -replace "时", "hrs"
$content = $content -replace "分", "min"
$content = $content -replace "秒", "sec"
$content = $content -replace "我们已经在一起", "Together"
$content = $content -replace "了！", ""

# Write back
$utf8 = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($filePath, $content, $utf8)
Write-Host "Fixed!"
