$filePath = "D:\love-for-yjh\frontend\src\App.tsx"
$content = [System.IO.File]::ReadAllText($filePath, [System.Text.Encoding]::UTF8)

# Fix corrupted strings - using simple string replacements
$content = $content -replace "title=\{isDark \? '[^\']*切换到浅色模式[^\']*' : '[^\']*切换到深色模式[^\']*'\}", "title={isDark ? 'Switch to light' : 'Switch to dark'}"
$content = $content -replace "\{isDark \? '[^\']*☀️[^\']*' : '[^\']*🌙[^\']*'\}", "{isDark ? 'Light' : 'Dark'}"
$content = $content -replace "注册成功！欢迎来到我们的小世界", "Registration successful! Welcome"
$content = $content -replace "欢迎回来，我最爱的人", "Welcome back, my love"
$content = $content -replace "我们的回忆", "Our Memories"
$content = $content -replace "地图足迹", "Map"
$content = $content -replace "时光胶囊", "Time Capsule"
$content = $content -replace "和解", "Reconcile"
$content = $content -replace "缐廷华", "Xian Tinghua"
$content = $content -replace "阳婧欢", "Yang Jinghuan"
$content = $content -replace "我们的爱情故事", "Our Love Story"
$content = $content -replace "悄悄话已送达", "Message sent"
$content = $content -replace "发送失败", "Send failed"
$content = $content -replace "请重试", "Please retry"
$content = $content -replace "正在为你准备最甜蜜的情话", "Preparing sweet words"
$content = $content -replace "加载中", "Loading"
$content = $content -replace "换一句情话", "Change quote"
$content = $content -replace "还没有回忆", "No memories yet"
$content = $content -replace "点击前往", "Go to"
$content = $content -replace "上传照片", "upload photos"
$content = $content -replace "写下你想对TA说的话", "Write something to your love"
$content = $content -replace "每一句话，都是真心话", "Every word is sincere"
$content = $content -replace "永远相爱", "Forever in love"
$content = $content -replace "照片上传成功", "Photo uploaded"
$content = $content -replace "已删除", "Deleted"
$content = $content -replace "已收藏.*珍贵瞬间", "precious moments"
$content = $content -replace "记录属于我们的每一个瞬间", "Record our precious moments"
$content = $content -replace "上传照片", "Upload Photo"
$content = $content -replace "还没有照片", "No photos yet"
$content = $content -replace "上传你们的第一张合照，让回忆永远留在这里", "Upload your first photo"
$content = $content -replace "视频上传成功", "Video uploaded"
$content = $content -replace "珍藏.*珍贵视频", "precious videos"
$content = $content -replace "记录属于我们的珍贵视频", "Record our precious videos"
$content = $content -replace "还没有视频", "No videos yet"
$content = $content -replace "上传你们的第一段视频，让美好永远留在这里", "Upload your first video"
$content = $content -replace "我们的美好时光", "Our Precious Time"
$content = $content -replace "YYYY年MM月DD日 HH:mm", "YYYY-MM-DD HH:mm"
$content = $content -replace "更新成功", "Updated"
$content = $content -replace "添加成功", "Added"
$content = $content -replace "记录每一个重要的日子，让爱有迹可循", "Record every important day"
$content = $content -replace "快去添加你们的第一个重要日子吧", "Add your first important day"
$content = $content -replace "YYYY年MM月DD日", "YYYY-MM-DD"
$content = $content -replace "编辑纪念日", "Edit"
$content = $content -replace "添加纪念日", "Add Memory"
$content = $content -replace "纪念日名称", "Title"
$content = $content -replace "请输入名称", "Enter title"
$content = $content -replace "保存修改", "Save"
$content = $content -replace "添加纪念日 🎉", "Add Memory 🎉"
$content = $content -replace "保存成功", "Saved"
$content = $content -replace "头像更新成功", "Avatar updated"
$content = $content -replace "加载中\.\.\.", "Loading..."
$content = $content -replace "匿名", "Anonymous"
$content = $content -replace "你爱的人的名字", "Your love name"
$content = $content -replace "我的昵称", "My nickname"
$content = $content -replace "邮箱", "Email"
$content = $content -replace "未设置", "Not set"
$content = $content -replace "TA的名字", "Partner name"
$content = $content -replace "在一起天数", "Days together"
$content = $content -replace "开始日期", "Start date"
$content = $content -replace "我爱你", "I love you"
$content = $content -replace "无数次", "Countless"
$content = $content -replace "想你次数", "Times missed"
$content = $content -replace "快捷操作", "Quick Actions"
$content = $content -replace "纪念日", "Anniversary"
$content = $content -replace "我们已经在一起.*天了", "We have been together for days"
$content = $content -replace "\{ val: counter\.days, label: '天', glow: true \}", "{ val: counter.days, label: 'Days', glow: true }"
$content = $content -replace "\{ val: pad\(counter\.hours\), label: '时', glow: false \}", "{ val: pad(counter.hours), label: 'Hrs', glow: false }"
$content = $content -replace "\{ val: pad\(counter\.minutes\), label: '分', glow: false \}", "{ val: pad(counter.minutes), label: 'Min', glow: false }"
$content = $content -replace "\{ val: pad\(counter\.seconds\), label: '秒', glow: true \}", "{ val: pad(counter.seconds), label: 'Sec', glow: true }"
$content = $content -replace "const emojis = \['💕', '💗', '💖', '🌸', '🌹', '[^\]]*'🎀', '💛', '💞', '🎵'\];", "const emojis = ['💕', '💗', '💖', '🌸', '🌹', '🎀', '💛', '💞', '🎵'];"

# Write back
$utf8WithBom = New-Object System.Text.UTF8Encoding $true
[System.IO.File]::WriteAllText($filePath, $content, $utf8WithBom)
Write-Host "Done!"
